
name: php_test
version: 0.0.1
language: php
description: php Run test use `phpunit`
public: true
tags:
  - php
  - test
inputs:
  - name: FLOW_ENABLE_FAILURE
    editable: true
    options:
      - TRUE
      - FALSE
outputs:
script_path: ./run.sh  
  
template: |  
  
  